// Generated by https://quicktype.io

export interface MovieDetails {
    id:             number;
    title:          string;
    posterUrl:      string;
    backdropUrl:    string;
    rating:         number;
    overview:       string;
    tagline:        string;
    budget:         number;
    revenue:        null;
    imdbUrl:        null;
    tmdbUrl:        null;
    releaseDate:    string;
    runTime:        number;
    price:          null;
    favoritesCount: number;
    casts:          Cast[];
    genres:         Genre[];
}

export interface Cast {
    id:          number;
    name:        string;
    gender:      null;
    tmdbUrl:     null;
    profilePath: string;
    character:   string;
    movies:      null;
}

export interface Genre {
    id:   number;
    name: string;
}
